[phases.setup]
nixPkgs = ["php81", "composer2", "nodejs_20"]

[phases.build]
cmds = [
  "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
  "npm install",
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
